#!/usr/bin/env python
from quickfit import LinReg
from quickfit.quickfit_mixin import QuickFitMixin
import sklearn.linear_model
from jtutils import fix_broken_pipe

class LinRegCL(LinReg, QuickFitMixin):
    """
    Linear regression model from the command line
    """
    def __init__(self):
        self.readCL()
        if self.args.no_scale:
            self.no_scale = True
        else:
            self.no_scale = False

        args = {}
        if self.args.no_intercept:
            args["fit_intercept"] = False

        if self.args.alpha is not None:
            self.raw_mdl = sklearn.linear_model.Lasso(alpha=self.args.alpha, **args)
        else:
            self.raw_mdl = sklearn.linear_model.LassoCV(**args)

        super(LinRegCL,self).__init__()

if __name__ == "__main__":
    fix_broken_pipe()
    mdl = LinRegCL()
    mdl.main()
    mdl.print_model()
